server:
  port: 8080
spring:
  application:
    name: wax-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.10:3306/oauth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: wax
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1

  jackson:
    default-property-inclusion: non_null

debug: true

